#pragma once
#define X_KEY_SPACE              32					// Key Codes
#define X_KEY_APOSTROPHE         39					// Key Codes
#define X_KEY_COMMA              44					// Key Codes
#define X_KEY_MINUS              45					// Key Codes
#define X_KEY_PERIOD             46					// Key Codes
#define X_KEY_SLASH              47					// Key Codes
#define X_KEY_0                  48					// Key Codes
#define X_KEY_1                  49					// Key Codes
#define X_KEY_2                  50					// Key Codes
#define X_KEY_3                  51					// Key Codes
#define X_KEY_4                  52					// Key Codes
#define X_KEY_5                  53					// Key Codes
#define X_KEY_6                  54					// Key Codes
#define X_KEY_7                  55					// Key Codes
#define X_KEY_8                  56					// Key Codes
#define X_KEY_9                  57					// Key Codes
#define X_KEY_SEMICOLON          59					// Key Codes
#define X_KEY_EQUAL              61					// Key Codes
#define X_KEY_A                  65					// Key Codes
#define X_KEY_B                  66					// Key Codes
#define X_KEY_C                  67					// Key Codes
#define X_KEY_D                  68					// Key Codes
#define X_KEY_E                  69					// Key Codes
#define X_KEY_F                  70					// Key Codes
#define X_KEY_G                  71					// Key Codes
#define X_KEY_H                  72					// Key Codes
#define X_KEY_I                  73					// Key Codes
#define X_KEY_J                  74					// Key Codes
#define X_KEY_K                  75					// Key Codes
#define X_KEY_L                  76					// Key Codes
#define X_KEY_M                  77					// Key Codes
#define X_KEY_N                  78					// Key Codes
#define X_KEY_O                  79					// Key Codes
#define X_KEY_P                  80					// Key Codes
#define X_KEY_Q                  81					// Key Codes
#define X_KEY_R                  82					// Key Codes
#define X_KEY_S                  83					// Key Codes
#define X_KEY_T                  84					// Key Codes
#define X_KEY_U                  85					// Key Codes
#define X_KEY_V                  86					// Key Codes
#define X_KEY_W                  87					// Key Codes
#define X_KEY_X                  88					// Key Codes
#define X_KEY_Y                  89					// Key Codes
#define X_KEY_Z                  90					// Key Codes
#define X_KEY_LEFT_BRACKET       91					// Key Codes
#define X_KEY_BACKSLASH          92					// Key Codes
#define X_KEY_RIGHT_BRACKET      93					// Key Codes
#define X_KEY_GRAVE_ACCENT       96					// Key Codes
#define X_KEY_WORLD_1            161				// Key Codes
#define X_KEY_WORLD_2            162				// Key Codes
#define X_KEY_ESCAPE             256				// Key Codes
#define X_KEY_ENTER              257				// Key Codes
#define X_KEY_TAB                258				// Key Codes
#define X_KEY_BACKSPACE          259				// Key Codes
#define X_KEY_INSERT             260				// Key Codes
#define X_KEY_DELETE             261				// Key Codes
#define X_KEY_RIGHT              262				// Key Codes
#define X_KEY_LEFT               263				// Key Codes
#define X_KEY_DOWN               264				// Key Codes
#define X_KEY_UP                 265				// Key Codes
#define X_KEY_PAGE_UP            266				// Key Codes
#define X_KEY_PAGE_DOWN          267				// Key Codes
#define X_KEY_HOME               268				// Key Codes
#define X_KEY_END                269				// Key Codes
#define X_KEY_CAPS_LOCK          280				// Key Codes
#define X_KEY_SCROLL_LOCK        281				// Key Codes
#define X_KEY_NUM_LOCK           282				// Key Codes
#define X_KEY_PRINT_SCREEN       283				// Key Codes
#define X_KEY_PAUSE              284				// Key Codes
#define X_KEY_F1                 290				// Key Codes
#define X_KEY_F2                 291				// Key Codes
#define X_KEY_F3                 292				// Key Codes
#define X_KEY_F4                 293				// Key Codes
#define X_KEY_F5                 294				// Key Codes
#define X_KEY_F6                 295				// Key Codes
#define X_KEY_F7                 296				// Key Codes
#define X_KEY_F8                 297				// Key Codes
#define X_KEY_F9                 298				// Key Codes
#define X_KEY_F10                299				// Key Codes
#define X_KEY_F11                300				// Key Codes
#define X_KEY_F12                301				// Key Codes
#define X_KEY_F13                302				// Key Codes
#define X_KEY_F14                303				// Key Codes
#define X_KEY_F15                304				// Key Codes
#define X_KEY_F16                305				// Key Codes
#define X_KEY_F17                306				// Key Codes
#define X_KEY_F18                307				// Key Codes
#define X_KEY_F19                308				// Key Codes
#define X_KEY_F20                309				// Key Codes
#define X_KEY_F21                310				// Key Codes
#define X_KEY_F22                311				// Key Codes
#define X_KEY_F23                312				// Key Codes
#define X_KEY_F24                313				// Key Codes
#define X_KEY_F25                314				// Key Codes
#define X_KEY_KP_0               320				// Key Codes
#define X_KEY_KP_1               321				// Key Codes
#define X_KEY_KP_2               322				// Key Codes
#define X_KEY_KP_3               323				// Key Codes
#define X_KEY_KP_4               324				// Key Codes
#define X_KEY_KP_5               325				// Key Codes
#define X_KEY_KP_6               326				// Key Codes
#define X_KEY_KP_7               327				// Key Codes
#define X_KEY_KP_8               328				// Key Codes
#define X_KEY_KP_9               329				// Key Codes
#define X_KEY_KP_DECIMAL         330				// Key Codes
#define X_KEY_KP_DIVIDE          331				// Key Codes
#define X_KEY_KP_MULTIPLY        332				// Key Codes
#define X_KEY_KP_SUBTRACT        333				// Key Codes
#define X_KEY_KP_ADD             334				// Key Codes
#define X_KEY_KP_ENTER           335				// Key Codes
#define X_KEY_KP_EQUAL           336				// Key Codes
#define X_KEY_LEFT_SHIFT         340				// Key Codes
#define X_KEY_LEFT_CONTROL       341				// Key Codes
#define X_KEY_LEFT_ALT           342				// Key Codes
#define X_KEY_LEFT_MASTER        343				// Key Codes
#define X_KEY_RIGHT_SHIFT        344				// Key Codes
#define X_KEY_RIGHT_CONTROL      345				// Key Codes
#define X_KEY_RIGHT_ALT          346				// Key Codes
#define X_KEY_RIGHT_MASTER       347				// Key Codes
#define X_KEY_MENU               348				// Key Codes
#define X_MOUSE_BUTTON_1         0					// Mouse Codes
#define X_MOUSE_BUTTON_2         1					// Mouse Codes
#define X_MOUSE_BUTTON_3         2					// Mouse Codes
#define X_MOUSE_BUTTON_4         3					// Mouse Codes
#define X_MOUSE_BUTTON_5         4					// Mouse Codes
#define X_MOUSE_BUTTON_6         5					// Mouse Codes
#define X_MOUSE_BUTTON_7         6					// Mouse Codes
#define X_MOUSE_BUTTON_8         7					// Mouse Codes
#define X_MOUSE_BUTTON_LAST      X_MOUSE_BUTTON_8	// Mouse Codes
#define X_MOUSE_BUTTON_LEFT      X_MOUSE_BUTTON_1	// Mouse Codes
#define X_MOUSE_BUTTON_RIGHT     X_MOUSE_BUTTON_2	// Mouse Codes
#define X_MOUSE_BUTTON_MIDDLE    X_MOUSE_BUTTON_3	// Mouse Codes