// X-Engine Library
//#include "XEngine/Core/EntryPoint.h"
#pragma once
#include <stdio.h>
#include "XEngine/Core/Time.h"
#include "XEngine/LogSystem/Log.h"
#include "XEngine/Core/Application.h"
#include "XEngine/InputSystem/Input.h"
#include "XEngine/LayerSystem/Layer.h"
#include "XEngine/ImGuiLayer/ImGuiLayer.h"
#include "XEngine/GraphicsSystem/Buffer.h"
#include "XEngine/GraphicsSystem/Camera.h"
#include "XEngine/GraphicsSystem/Shader.h"
#include "XEngine/GraphicsSystem/Texture.h"
#include "XEngine/GraphicsSystem/VertexArray.h"
#include "XEngine/InputSystem/XEngineInputCodes.h"
#include "XEngine/GraphicsSystem/CameraController.h"
#include "XEngine/GraphicsSystem/Renderer/Renderer.h"
#include "XEngine/GraphicsSystem/Renderer/RenderCommand.h"